/**
 * Author:  FV
 * Created: May 5, 2022
 */

<--TABLE INITIALIZATION-->
CREATE SCHEMA UAAP_APPAREL;

CREATE TABLE USER_TABLE(USER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
USER_PASSWORD VARCHAR(1000) NOT NULL,
USER_ROLE VARCHAR(45) NOT NULL,
USER_EMAIL VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE PRODUCT_TABLE (
PRODUCT_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1), 
PRODUCT_NAME VARCHAR(50) NOT NULL, 
PRODUCT_DESC VARCHAR(1000),
PRODUCT_SCHOOL VARCHAR(50) NOT NULL,
PRODUCT_CATEGORY VARCHAR (50) NOT NULL,
PRODUCT_IMG_LINK VARCHAR(1000) NOT NULL
);

CREATE TABLE PRODUCT_SIZE_TABLE(
PRODUCT_SIZE_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (Start with 1, Increment by 1),
PRODUCT_SIZE VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCT_GENDER_TABLE(
PRODUCT_GENDER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (Start with 1, Increment by 1),
PRODUCT_GENDER VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCT_VARIANT_TABLE (
VARIANT_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
PRODUCT_ID INT NOT NULL REFERENCES PRODUCT_TABLE(PRODUCT_ID),
PRODUCT_GENDER_ID INT NOT NULL REFERENCES PRODUCT_GENDER_TABLE(PRODUCT_GENDER_ID),
PRODUCT_SIZE_ID INT NOT NULL REFERENCES PRODUCT_SIZE_TABLE(PRODUCT_SIZE_ID),
PRODUCT_PRICE INT NOT NULL,
PRODUCT_STOCK INT NOT NULL
);

CREATE TABLE ORDER_TABLE (ORDER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
USER_ID INTEGER NOT NULL REFERENCES USER_TABLE(USER_ID),
ORDER_NAME VARCHAR(50) NOT NULL,
ORDER_QUANTITY INTEGER NOT NULL,
ORDER_PRICE INTEGER NOT NULL,
ORDER_ADDRESS VARCHAR(1000) NOT NULL,
ORDER_DATE DATE NOT NULL,
ORDER_DATE_COMPLETED DATE,
ORDER_ISPAID BOOLEAN,
ORDER_IMG_LINK VARCHAR(1000)
);

<--END INITIALIZAITON-->